# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-PrintDialog
version:      0.02
version_from: lib/Gtk2/Ex/PrintDialog.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Spec:                    0
    File::Temp:                    0
    Gtk2:                          0
    Locale::gettext:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
